#!/usr/bin/env bash
#---------------------------------------------------------------------
# Pyplate environment init script
#    
#---------------------------------------------------------------------
#

#set -o xtrace   # Display commands as they are executed
#set -o pipefail # Exit script when pipe fails

# Directory where script is located
scriptPath=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#---------------------------------------------------------------------

# Add script path to global path
export PATH=${PATH}:${scriptPath}:${scriptPath}

