#!/usr/bin/env bash
#---------------------------------------------------------------------
# Bashplate environment init script
#
#---------------------------------------------------------------------
# Use:
# Run this from .bashrc file.
#
# source pathToThisFile/pyplate_init
#
#


#set -o xtrace   # Display commands as they are executed
#set -o pipefail # Exit script when pipe fails

# Directory where script is located
scriptPath=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#---------------------------------------------------------------------

																			
# Add bashplate dir to search path
export PATH=${PATH}:${scriptPath}

# Add alias 
#alias bpd='cd ${BP_PATH}'




